### ISSUE TITLE
Possible compatibility issue with Vaadin 23.2

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/AppLayoutAddon#105]
When using this addon in a Vaadin 23.2 application, Vite fails with the following error:

```
 X [ERROR] [plugin vite:dep-pre-bundle] Missing "./lib/shady-render.js" export in "lit-html" package
 
     node_modules/lit-element/lit-element.js:56:23:
       56 │ import { render } from 'lit-html/lib/shady-render.js';
          ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
   This error came from the "onResolve" callback registered here:
 
     node_modules/.pnpm/esbuild@0.15.10/node_modules/esbuild/lib/main.js:1251:20:
       1251 │       let promise = setup({
            ╵                     ^
 
     at setup (file:///J:/workspaces/webapp-vaadin-23/node_modules/.pnpm/vite@3.1.0/node_modules/vite/dist/node/chunks/dep-665b0112.js:35015:19)
     at handlePlugins (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:1251:21)
     at buildOrServeImpl (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:942:5)
     at Object.buildOrServe (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:750:5)
     at J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:2085:17
     at new Promise (<anonymous>)
     at Object.build (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:2084:14)
     at build (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:1931:51)
     at runOptimizeDeps (file:///J:/workspaces/webapp-vaadin-23/node_modules/.pnpm/vite@3.1.0/node_modules/vite/dist/node/chunks/dep-665b0112.js:42288:26)
 
 
 X [ERROR] [plugin vite:dep-pre-bundle] Missing "./lit-html.js" export in "lit-html" package
 
     node_modules/lit-element/lit-element.js:61:61:
       61 │ ..., TemplateResult, SVGTemplateResult } from 'lit-html/lit-html.js';
          ╵                                               ~~~~~~~~~~~~~~~~~~~~~~
 
   This error came from the "onResolve" callback registered here:
 
     node_modules/.pnpm/esbuild@0.15.10/node_modules/esbuild/lib/main.js:1251:20:
       1251 │       let promise = setup({
            ╵                     ^
 
     at setup (file:///J:/workspaces/webapp-vaadin-23/node_modules/.pnpm/vite@3.1.0/node_modules/vite/dist/node/chunks/dep-665b0112.js:35015:19)
     at handlePlugins (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:1251:21)
     at buildOrServeImpl (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:942:5)
     at Object.buildOrServe (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:750:5)
     at J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:2085:17
     at new Promise (<anonymous>)
     at Object.build (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:2084:14)
     at build (J:\workspaces\webapp-vaadin-23\node_modules\.pnpm\esbuild@0.15.10\node_modules\esbuild\lib\main.js:1931:51)
     at runOptimizeDeps (file:///J:/workspaces/webapp-vaadin-23/node_modules/.pnpm/vite@3.1.0/node_modules/vite/dist/node/chunks/dep-665b0112.js:42288:26)
```

If AppLayoutAddon is removed from the application, it starts with no error. However, I have not been able to reproduce it in a starter application.

**Comment by mlopezFC** [comment]
Couldn't reproduce it in addons demos either so closing it for now.
